import { FormEvent, useEffect, useMemo, useState } from 'react';
import './App.css';

type Role = 'staff' | 'pm' | 'admin';
type WorkType = 'Work' | 'Annual Leave' | 'Sick Leave' | 'RDO' | 'Public Holiday' | 'Training' | 'Other Paid Leave';
type Status = 'Submitted' | 'PM Approved' | 'Admin Approved' | 'Rejected';
type User = { employeeId:string; name:string; email:string; role:Role; position:string; mustChangePassword:boolean };
type StaffRow = { employeeId:string; name:string; email:string; position:string; role:Role; active:boolean; mustChangePassword:boolean };
type Entry = { id:string; employeeId:string; employee:string; date:string; type:WorkType; jobNumber:string; start:string; finish:string; breakMinutes:number; totalHours:number; notes:string; status:Status; pmApprovedBy?:string; adminApprovedBy?:string; rejectionReason?:string; createdAt:string; simproStatus?:string };
const workTypes:WorkType[]=['Work','Annual Leave','Sick Leave','RDO','Public Holiday','Training','Other Paid Leave'];
function hoursBetween(start:string,finish:string,breakMinutes:number){if(!start||!finish)return 0;const[sh,sm]=start.split(':').map(Number),[fh,fm]=finish.split(':').map(Number);let mins=fh*60+fm-(sh*60+sm)-breakMinutes;if(mins<0)mins+=1440;return Math.max(0,Math.round(mins/60*100)/100)}
function roleLabel(role:Role){return role==='pm'?'Project Manager':role==='admin'?'Office Admin':'Staff'}
function statusClass(status:string){return status.toLowerCase().replace(/ /g,'-')}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const res=await fetch(path,{...init,credentials:'same-origin',headers:{'Content-Type':'application/json',...(init?.headers||{})}});const text=await res.text();if(!res.ok){let msg=text||'Request failed';try{msg=JSON.parse(text).error||msg}catch{}throw new Error(msg)}return(text?JSON.parse(text):{}) as T}

export default function App(){
 const[user,setUser]=useState<User|null>(null),[entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const[login,setLogin]=useState({identifier:'',password:''}),[showOfficeSetup,setShowOfficeSetup]=useState(false),[setup,setSetup]=useState({identifier:'',code:'',password:''});
 const[password,setPassword]=useState({currentPassword:'',newPassword:''});
 const[showLoginPassword,setShowLoginPassword]=useState(false),[showSetupCode,setShowSetupCode]=useState(false),[showSetupPassword,setShowSetupPassword]=useState(false),[showCurrentPassword,setShowCurrentPassword]=useState(false),[showNewPassword,setShowNewPassword]=useState(false);
 const[staff,setStaff]=useState<StaffRow[]>([]),[staffSearch,setStaffSearch]=useState(''),[temporary,setTemporary]=useState<{name:string;password:string}|null>(null);
 const[form,setForm]=useState({date:new Date().toISOString().slice(0,10),type:'Work' as WorkType,jobNumber:'',start:'07:00',finish:'15:30',breakMinutes:30,notes:''});
 const total=useMemo(()=>hoursBetween(form.start,form.finish,Number(form.breakMinutes)),[form]);
 async function refresh(){const data=await api<{entries:Entry[]}>('/api/timesheets');setEntries(data.entries)}
 async function loadStaff(){if(user?.role!=='admin')return;const data=await api<{staff:StaffRow[]}>('/api/admin/staff');setStaff(data.staff)}
 async function loadSession(){try{const data=await api<{user:User}>('/api/auth/me');setUser(data.user);if(!data.user.mustChangePassword)await refresh()}catch{setUser(null);setEntries([])}finally{setLoading(false)}}
 useEffect(()=>{
  document.title='Elliot Timesheets';
  const ensureLink=(rel:string,href:string)=>{let el=document.querySelector(`link[rel="${rel}"]`) as HTMLLinkElement|null;if(!el){el=document.createElement('link');el.rel=rel;document.head.appendChild(el)}el.href=href};
  const ensureMeta=(name:string,content:string)=>{let el=document.querySelector(`meta[name="${name}"]`) as HTMLMetaElement|null;if(!el){el=document.createElement('meta');el.name=name;document.head.appendChild(el)}el.content=content};
  ensureLink('manifest','/manifest.webmanifest');
  ensureLink('apple-touch-icon','/icons/apple-touch-icon.png');
  ensureMeta('theme-color','#0f1b26');
  ensureMeta('apple-mobile-web-app-capable','yes');
  ensureMeta('apple-mobile-web-app-status-bar-style','black-translucent');
  ensureMeta('apple-mobile-web-app-title','Elliot Timesheets');
  if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{});}
  loadSession();
 },[]);
 useEffect(()=>{if(user?.role==='admin'&&!user.mustChangePassword)loadStaff()},[user?.role,user?.mustChangePassword]);
 async function signIn(e:FormEvent){e.preventDefault();setMessage('');try{const data=await api<{user:User}>('/api/auth/login',{method:'POST',body:JSON.stringify(login)});setUser(data.user);setLogin({identifier:'',password:''});setMessage(`Signed in as ${data.user.name}.`);if(!data.user.mustChangePassword)await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Could not sign in')}}
 async function bootstrap(e:FormEvent){e.preventDefault();setMessage('');try{const data=await api<{user:User}>('/api/auth/bootstrap-admin',{method:'POST',body:JSON.stringify(setup)});setUser(data.user);setSetup({identifier:'',code:'',password:''});setShowOfficeSetup(false);setMessage('Office Admin account created.');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Could not complete Office setup')}}
 async function changePassword(e:FormEvent){e.preventDefault();setMessage('');try{const data=await api<{user:User}>('/api/auth/change-password',{method:'POST',body:JSON.stringify(password)});setUser(data.user);setPassword({currentPassword:'',newPassword:''});setMessage('Password changed.');await refresh();if(data.user.role==='admin')await loadStaff()}catch(e){setMessage(e instanceof Error?e.message:'Could not change password')}}
 async function logout(){await api('/api/auth/logout',{method:'POST'});setUser(null);setEntries([]);setStaff([]);setMessage('Signed out.')}
 async function submit(e:FormEvent){e.preventDefault();setMessage('');if(form.type==='Work'&&!form.jobNumber.trim())return setMessage('Simpro job number is required for worked time.');if(total<=0)return setMessage('Check start and finish times.');try{await api('/api/timesheets',{method:'POST',body:JSON.stringify({...form,breakMinutes:Number(form.breakMinutes),totalHours:total})});setMessage('Timesheet submitted for PM approval.');setForm(f=>({...f,jobNumber:'',notes:''}));await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Could not submit timesheet')}}
 async function action(id:string,actionName:'pm-approve'|'admin-approve'|'reject'){let reason='';if(actionName==='reject')reason=window.prompt('Reason for rejection?')||'Rejected';try{await api(`/api/timesheets/${id}`,{method:'PATCH',body:JSON.stringify({action:actionName,reason})});await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Could not update timesheet')}}
 async function staffAction(employeeId:string,actionName:'activate'|'reset-password'|'deactivate'){setMessage('');setTemporary(null);try{const data=await api<{ok:boolean;tempPassword?:string;employee?:{name:string}}>(`/api/admin/staff/${employeeId}/${actionName}`,{method:'POST'});if(data.tempPassword&&data.employee)setTemporary({name:data.employee.name,password:data.tempPassword});setMessage(actionName==='deactivate'?'Account deactivated.':actionName==='activate'?'Account activated. Give the temporary password to the employee.':'Temporary password reset. Give the new password to the employee.');await loadStaff()}catch(e){setMessage(e instanceof Error?e.message:'Could not update staff account')}}
 async function setRole(employeeId:string,role:Role){try{await api(`/api/admin/staff/${employeeId}/role`,{method:'PATCH',body:JSON.stringify({role})});setMessage('Staff role updated.');await loadStaff()}catch(e){setMessage(e instanceof Error?e.message:'Could not update role')}}
 if(loading)return <div className="center-screen"><div className="loader-card"><strong>ELLIOT CONTROLS</strong><p>Loading timesheets…</p></div></div>;
 if(!user)return <div className="auth-shell"><div className="auth-card"><div className="brand-kicker">ELLIOT CONTROLS</div><h1>Timesheets</h1><p className="muted">Staff sign in</p>{message&&<div className="message">{message}</div>}
  {!showOfficeSetup?<><form onSubmit={signIn} className="auth-form"><label>Full name or email<input value={login.identifier} onChange={e=>setLogin({...login,identifier:e.target.value})} placeholder="e.g. Aiden Elliot" required autoComplete="username"/></label><label>Password<PasswordInput shown={showLoginPassword} onToggle={()=>setShowLoginPassword(v=>!v)} value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required autoComplete="current-password"/></label><button className="primary" type="submit">Sign in</button></form><p className="small-note">Accounts are activated by Office Admin. You do not need your Simpro Employee ID.</p><button className="text-button" onClick={()=>{setShowOfficeSetup(true);setMessage('')}}>Office Admin setup</button></>
  :<><form onSubmit={bootstrap} className="auth-form"><label>Office Admin name or email<input value={setup.identifier} onChange={e=>setSetup({...setup,identifier:e.target.value})} placeholder="Office Admin from staff list" required/></label><label>Private setup code<PasswordInput shown={showSetupCode} onToggle={()=>setShowSetupCode(v=>!v)} value={setup.code} onChange={e=>setSetup({...setup,code:e.target.value})} required/></label><label>Create Office Admin password<PasswordInput shown={showSetupPassword} onToggle={()=>setShowSetupPassword(v=>!v)} value={setup.password} onChange={e=>setSetup({...setup,password:e.target.value})} minLength={10} required/></label><button className="primary" type="submit">Complete Office setup</button></form><p className="small-note">This setup works once and requires the private code stored in Cloudflare.</p><button className="text-button" onClick={()=>{setShowOfficeSetup(false);setMessage('')}}>Back to staff sign in</button></>}</div></div>;
 if(user.mustChangePassword)return <div className="auth-shell"><div className="auth-card"><div className="brand-kicker">ELLIOT CONTROLS</div><h1>Choose your password</h1><p className="muted">Hi {user.name}. Replace the temporary password Office gave you.</p>{message&&<div className="message">{message}</div>}<form onSubmit={changePassword} className="auth-form"><label>Temporary password<PasswordInput shown={showCurrentPassword} onToggle={()=>setShowCurrentPassword(v=>!v)} value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})} required/></label><label>New password<PasswordInput shown={showNewPassword} onToggle={()=>setShowNewPassword(v=>!v)} value={password.newPassword} onChange={e=>setPassword({...password,newPassword:e.target.value})} minLength={10} required/></label><button className="primary" type="submit">Save my password</button></form><button className="text-button" onClick={logout}>Sign out</button></div></div>;
 const myEntries=entries.filter(e=>e.employeeId===user.employeeId);const queue=user.role==='pm'?entries.filter(e=>e.status==='Submitted'&&e.employeeId!==user.employeeId):user.role==='admin'?entries.filter(e=>e.status==='PM Approved'):[];
 const filteredStaff=staff.filter(s=>`${s.name} ${s.email} ${s.position}`.toLowerCase().includes(staffSearch.toLowerCase()));
 return <div className="app-shell"><header className="topbar"><div><div className="brand-kicker">ELLIOT CONTROLS</div><h1>Timesheets</h1></div><div className="account"><div><strong>{user.name}</strong><span>{roleLabel(user.role)}</span></div><button onClick={logout}>Sign out</button></div></header><main className="page">{message&&<div className="message">{message}</div>}
  <section className="card"><div className="section-head"><div><span className="eyebrow">NEW ENTRY</span><h2>Enter time</h2></div><strong>{total.toFixed(2)} hrs</strong></div><form onSubmit={submit} className="form-grid"><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Type<select value={form.type} onChange={e=>{const type=e.target.value as WorkType;setForm({...form,type,breakMinutes:type==='Work'?30:0,jobNumber:type==='Work'?form.jobNumber:''})}}>{workTypes.map(t=><option key={t}>{t}</option>)}</select></label>{form.type==='Work'&&<label className="wide">Simpro job number *<input value={form.jobNumber} onChange={e=>setForm({...form,jobNumber:e.target.value})} placeholder="Required" inputMode="numeric"/></label>}<label>Start<input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Finish<input type="time" value={form.finish} onChange={e=>setForm({...form,finish:e.target.value})}/></label><label>Break (minutes)<input type="number" min="0" max="240" value={form.breakMinutes} onChange={e=>setForm({...form,breakMinutes:Number(e.target.value)})}/></label><label className="wide">Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optional"/></label><button className="primary wide" type="submit">Submit timesheet</button></form></section>
  {user.role!=='staff'&&<section className="card"><div className="section-head"><div><span className="eyebrow">{user.role==='pm'?'PM APPROVAL QUEUE':'OFFICE ADMIN QUEUE'}</span><h2>Waiting for your approval</h2></div><button className="ghost" onClick={refresh}>Refresh</button></div>{queue.length===0?<p className="muted">Nothing waiting for approval.</p>:<div className="entry-list">{queue.map(e=><EntryCard key={e.id} entry={e} user={user} action={action}/>)}</div>}</section>}
  {user.role==='admin'&&<section className="card"><div className="section-head"><div><span className="eyebrow">OFFICE ADMIN</span><h2>Manage staff accounts</h2></div><button className="ghost" onClick={loadStaff}>Refresh</button></div><input className="staff-search" value={staffSearch} onChange={e=>setStaffSearch(e.target.value)} placeholder="Search name, email or position"/>{temporary&&<div className="temporary"><strong>Temporary password for {temporary.name}</strong><code>{temporary.password}</code><span>Copy this now. It is only shown after activation/reset.</span></div>}<div className="staff-list">{filteredStaff.map(s=><div className="staff-row" key={s.employeeId}><div className="staff-person"><strong>{s.name}</strong><span>{s.position||'No position'} • Simpro #{s.employeeId}</span><span>{s.email}</span></div><div className="staff-controls"><select value={s.role} onChange={e=>setRole(s.employeeId,e.target.value as Role)} aria-label={`Role for ${s.name}`}><option value="staff">Staff</option><option value="pm">Project Manager</option><option value="admin">Office Admin</option></select><span className={`account-status ${s.active?'active':'inactive'}`}>{s.active?(s.mustChangePassword?'Temp password issued':'Active'):'Not activated'}</span>{s.active?<><button className="ghost" onClick={()=>staffAction(s.employeeId,'reset-password')}>Reset password</button><button className="danger" onClick={()=>staffAction(s.employeeId,'deactivate')}>Deactivate</button></>:<button className="primary" onClick={()=>staffAction(s.employeeId,'activate')}>Activate</button>}</div></div>)}</div></section>}
  <section className="card"><div className="section-head"><div><span className="eyebrow">MY TIMESHEETS</span><h2>Recent entries</h2></div><button className="ghost" onClick={refresh}>Refresh</button></div>{myEntries.length===0?<p className="muted">No timesheets yet.</p>:<div className="entry-list">{myEntries.map(e=><EntryCard key={e.id} entry={e} user={user} action={action}/>)}</div>}</section><footer>Office-managed staff accounts • Simpro employee IDs linked in the background • Live Simpro posting awaits API approval.</footer></main></div>
}

function PasswordInput({shown,onToggle,...props}:{shown:boolean;onToggle:()=>void}&Omit<JSX.IntrinsicElements['input'],'type'>){
 return <div style={{position:'relative',width:'100%'}}><input {...props} type={shown?'text':'password'} style={{...(props.style||{}),paddingRight:'48px',width:'100%'}}/><button type="button" onClick={onToggle} aria-label={shown?'Hide password':'Show password'} title={shown?'Hide password':'Show password'} style={{position:'absolute',right:'10px',top:'50%',transform:'translateY(-50%)',border:0,background:'transparent',padding:'8px',cursor:'pointer',fontSize:'20px',lineHeight:1,color:'inherit'}}>{shown?'🙈':'👁️'}</button></div>
}

function EntryCard({entry,user,action}:{entry:Entry;user:User;action:(id:string,a:'pm-approve'|'admin-approve'|'reject')=>void}){return <div className="entry"><div><div className="entry-title"><strong>{entry.employee}</strong><span className={`badge status-${statusClass(entry.status)}`}>{entry.status}</span></div><div className="entry-meta"><span>{entry.date}</span><span>{entry.type}</span><span>{entry.start}–{entry.finish}</span><span>{entry.totalHours.toFixed(2)} hrs</span></div>{entry.jobNumber&&<div className="job">Job #{entry.jobNumber}</div>}{entry.notes&&<p>{entry.notes}</p>}{entry.status==='Admin Approved'&&<p className="simpro">Simpro: {entry.simproStatus||'Awaiting API connection'}</p>}{entry.rejectionReason&&<p className="rejected">Rejected: {entry.rejectionReason}</p>}</div><div className="actions">{user.role==='pm'&&entry.status==='Submitted'&&entry.employeeId!==user.employeeId&&<><button className="primary" onClick={()=>action(entry.id,'pm-approve')}>PM approve</button><button className="danger" onClick={()=>action(entry.id,'reject')}>Reject</button></>}{user.role==='admin'&&entry.status==='PM Approved'&&<><button className="primary" onClick={()=>action(entry.id,'admin-approve')}>Final approve</button><button className="danger" onClick={()=>action(entry.id,'reject')}>Reject</button></>}</div></div>}
